[package]
name = "xk-web-midair-haptic-driver-rust"
version = "0.1.0"
edition = "2021"
links = "UltraleapHaptics"

[dependencies]
# ulhaptics
cxx = "1.0"

# js
v8 = "0.60.1"
serde = "1.0.152"
serde_v8 = "0.82.0"

#websockets
tungstenite = "0.18.0"


[build-dependencies]
cxx-build = "1.0"