[package]
name = "xk-web-midair-haptic-driver-rust"
version = "0.1.0"
edition = "2021"
links = "UltraleapHaptics"

[dependencies]
crossbeam-channel = "0.5"
mah-pattern-evaluator = { path = "../mah-pattern-evaluator" }
serde = "1.0"
serde_json = "1.0"

# ulhaptics
cxx = "1.0"

#websockets
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync"] }
tokio-tungstenite = "0.18"
futures-util = "0.3"

[build-dependencies]
cxx-build = "1.0"